/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author emilio
 */
public class BarAdministrador extends javax.swing.JFrame {

    //Atributos
    String Nombre, Telefono, Ubicacion, parqueo, moneda,horario;

    /**
     * Creates new form BarAdministrador
     */
    public BarAdministrador() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Parqueo = new javax.swing.ButtonGroup();
        Moneda = new javax.swing.ButtonGroup();
        jFileChooser = new javax.swing.JFileChooser();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelUbicacion = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelParqueo = new javax.swing.JLabel();
        jLabelTipoDeMoneda = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldTelefono = new javax.swing.JTextField();
        Imagen = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaUbcacion = new javax.swing.JTextArea();
        jRadioButtonParqueoSi = new javax.swing.JRadioButton();
        jRadioButtonParqueoNo = new javax.swing.JRadioButton();
        jButtonAI = new javax.swing.JButton();
        jButtonAC = new javax.swing.JButton();
        jButtonAP = new javax.swing.JButton();
        jRadioButtonTDMC = new javax.swing.JRadioButton();
        jRadioButtonTDMD = new javax.swing.JRadioButton();
        jRadioButtonTDMA = new javax.swing.JRadioButton();
        Guardar = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNombre.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabelNombre.setText("Nombre");
        jPanel1.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabelUbicacion.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabelUbicacion.setText("Ubicacion");
        jPanel1.add(jLabelUbicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jLabelTelefono.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabelTelefono.setText("Telefono");
        jPanel1.add(jLabelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabelParqueo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabelParqueo.setText("Parqueo");
        jPanel1.add(jLabelParqueo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 500, -1, -1));

        jLabelTipoDeMoneda.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabelTipoDeMoneda.setText("Tipo de moneda");
        jPanel1.add(jLabelTipoDeMoneda, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, -1, -1));

        jTextFieldNombre.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jPanel1.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 330, -1));

        jTextFieldTelefono.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jPanel1.add(jTextFieldTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 330, -1));

        Imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SignoPregunta.jpg"))); // NOI18N
        jPanel1.add(Imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 250, 250));

        jTextAreaUbcacion.setColumns(20);
        jTextAreaUbcacion.setFont(new java.awt.Font("Ubuntu", 0, 14)); // NOI18N
        jTextAreaUbcacion.setRows(5);
        jScrollPane1.setViewportView(jTextAreaUbcacion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 350, 100));

        Parqueo.add(jRadioButtonParqueoSi);
        jRadioButtonParqueoSi.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jRadioButtonParqueoSi.setText("Si");
        jPanel1.add(jRadioButtonParqueoSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, -1, -1));

        Parqueo.add(jRadioButtonParqueoNo);
        jRadioButtonParqueoNo.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jRadioButtonParqueoNo.setText("No");
        jPanel1.add(jRadioButtonParqueoNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 570, -1, -1));

        jButtonAI.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jButtonAI.setText("Agregar Imagen");
        jPanel1.add(jButtonAI, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, -1, -1));

        jButtonAC.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jButtonAC.setText("Agregar comidas");
        jButtonAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonACActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAC, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, -1, -1));

        jButtonAP.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jButtonAP.setText("Agregar promociones");
        jButtonAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAPActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, -1, -1));

        Moneda.add(jRadioButtonTDMC);
        jRadioButtonTDMC.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jRadioButtonTDMC.setText("Colones");
        jPanel1.add(jRadioButtonTDMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 670, -1, -1));

        Moneda.add(jRadioButtonTDMD);
        jRadioButtonTDMD.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jRadioButtonTDMD.setText("Dolares");
        jPanel1.add(jRadioButtonTDMD, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 700, -1, -1));

        Moneda.add(jRadioButtonTDMA);
        jRadioButtonTDMA.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jRadioButtonTDMA.setText("Ambos");
        jPanel1.add(jRadioButtonTDMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 730, -1, -1));

        Guardar.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        jPanel1.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 730, -1, -1));

        Volver.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        Volver.setText("Volver");
        jPanel1.add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 730, -1, -1));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setText("Horario");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jTextField1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 330, -1));

        jButton1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jButton1.setText("Modificar Datos");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 600, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 800));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonACActionPerformed
        // TODO add your handling code here:
        AgregarComidas comidas = new AgregarComidas();
        comidas.setVisible(true);

    }//GEN-LAST:event_jButtonACActionPerformed

    private void jButtonAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAPActionPerformed
        // TODO add your handling code here:
        AgregarPromos promos = new AgregarPromos();
        promos.setVisible(true);
    }//GEN-LAST:event_jButtonAPActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        Nombre = jTextFieldNombre.getText();
        Telefono = jTextFieldTelefono.getText();
        Ubicacion = jTextAreaUbcacion.getText();
        horario = jTextField1.getText();
        if (jRadioButtonParqueoSi.isSelected()) {
            parqueo = "Si";
        } else if (jRadioButtonParqueoNo.isSelected()) {
            parqueo = "No";
        }

        if (jRadioButtonTDMC.isSelected()) {
            moneda = "Colones";
        } else {
            if (jRadioButtonTDMD.isSelected()) {
                moneda = "Dolares";
            } else {
                if (jRadioButtonTDMA.isSelected()) {
                    moneda = "Colones o Dolares";
                }
            }
        }
    }//GEN-LAST:event_GuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BarAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BarAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BarAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BarAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BarAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Guardar;
    private javax.swing.JLabel Imagen;
    private javax.swing.ButtonGroup Moneda;
    private javax.swing.ButtonGroup Parqueo;
    private javax.swing.JButton Volver;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAC;
    private javax.swing.JButton jButtonAI;
    private javax.swing.JButton jButtonAP;
    private javax.swing.JFileChooser jFileChooser;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelParqueo;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JLabel jLabelTipoDeMoneda;
    private javax.swing.JLabel jLabelUbicacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonParqueoNo;
    private javax.swing.JRadioButton jRadioButtonParqueoSi;
    private javax.swing.JRadioButton jRadioButtonTDMA;
    private javax.swing.JRadioButton jRadioButtonTDMC;
    private javax.swing.JRadioButton jRadioButtonTDMD;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaUbcacion;
    private javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
