
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cr270
 */

public class EventoAdministradorAgregar extends javax.swing.JFrame {
    int contador;
    static String agregaNombre;
    static String agregaUbicacion ;
    static float agregaPrecio;
    static int agregaCantidad ;
    static String agregaArtista;
    static String direccion;
    static String direccion2;
    static String direccion3;
    /**
     * Creates new form EventoAdministradorAgregar
     */
    public EventoAdministradorAgregar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButtonFoto1 = new javax.swing.JButton();
        jButtonFoto2 = new javax.swing.JButton();
        jButtonFoto3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("AGREGA LA INFORMACION DE TU EVENTO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel2.setText("Nombre del evento");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setText("Ubicacion del evento");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel4.setText("Precio del evento");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel5.setText("Capacidad de personas");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel6.setText("Artista en Evento");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel7.setText("Musica en Evento");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 150, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 150, -1));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 150, -1));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 150, -1));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 150, -1));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electro", "Reguetton", "Rock", "Jazz", "Otro" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 150, -1));

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 600, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel8.setText("Fotos del Evento");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 120, -1));

        jButtonFoto1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonFoto1.setText("Escoger Foto");
        jButtonFoto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFoto1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFoto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 520, -1, 30));

        jButtonFoto2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonFoto2.setText("Escoger Foto 2");
        jButtonFoto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFoto2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFoto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 520, -1, 30));

        jButtonFoto3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonFoto3.setText("Escoger Foto 3");
        jButtonFoto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFoto3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonFoto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 520, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        if(AgregarFoto.insertaFoto == true){
            agregaNombre = jTextField1.getText();
            agregaUbicacion = jTextField2.getText();
            agregaPrecio = Float.parseFloat(jTextField3.getText());
            agregaCantidad = Integer.parseInt(jTextField4.getText());
            agregaArtista = jTextField5.getText();

           EventoAdministrador obj1 = new EventoAdministrador(agregaNombre,agregaUbicacion,agregaCantidad,agregaPrecio,agregaArtista);
           EventoAdministradorVerEventos obj2 = new EventoAdministradorVerEventos();
           this.dispose();
           obj2.setVisible(true);
        }        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonFoto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFoto1ActionPerformed
       
       int resultado;
       File fichero;
       AgregarFoto obj1= new AgregarFoto();
       FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG y PNG", "jpg", "png");
       AgregarFoto.jFileCambia.setFileFilter(filtro);
       AgregarFoto.jFileCambia.setAcceptAllFileFilterUsed(false);
       resultado = AgregarFoto.jFileCambia.showOpenDialog(null);
       
         if (JFileChooser.APPROVE_OPTION == resultado) {
            fichero = obj1.jFileCambia.getSelectedFile();
            direccion = fichero.getPath();
         }
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonFoto1ActionPerformed

    private void jButtonFoto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFoto2ActionPerformed
       int resultado;
       File fichero2;
       AgregarFoto obj2= new AgregarFoto();
       FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG y PNG", "jpg", "png");
       AgregarFoto.jFileCambia.setFileFilter(filtro);
       AgregarFoto.jFileCambia.setAcceptAllFileFilterUsed(false);
       resultado = AgregarFoto.jFileCambia.showOpenDialog(null);
       
         if (JFileChooser.APPROVE_OPTION == resultado) {
            fichero2 = obj2.jFileCambia.getSelectedFile();
            direccion2 = fichero2.getPath();
         }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFoto2ActionPerformed

    private void jButtonFoto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFoto3ActionPerformed

        int resultado;
       File fichero3;
       AgregarFoto obj3= new AgregarFoto();
       FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG y PNG", "jpg", "png");
       AgregarFoto.jFileCambia.setFileFilter(filtro);
       AgregarFoto.jFileCambia.setAcceptAllFileFilterUsed(false);
       resultado = AgregarFoto.jFileCambia.showOpenDialog(null);
       
         if (JFileChooser.APPROVE_OPTION == resultado) {
            fichero3 = obj3.jFileCambia.getSelectedFile();
            direccion3 = fichero3.getPath();
         }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFoto3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventoAdministradorAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventoAdministradorAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventoAdministradorAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventoAdministradorAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventoAdministradorAgregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonFoto1;
    private javax.swing.JButton jButtonFoto2;
    private javax.swing.JButton jButtonFoto3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
