
import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cr270
 */

public class EventoAdministradorAgregar extends javax.swing.JFrame {
    int contador;
    static String agregaNombre;
    static String agregaUbicacion ;
    static float agregaPrecio;
    static int agregaCantidad ;
    static String agregaArtista;
    static String direccion;
    static String direccion2;
    static String direccion3;
    /**
     * Creates new form EventoAdministradorAgregar
     */
    public EventoAdministradorAgregar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nombreEvento = new javax.swing.JTextField();
        ubicacionEvento = new javax.swing.JTextField();
        precioEvento = new javax.swing.JTextField();
        capacidadEvento = new javax.swing.JTextField();
        artistaEvento = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButtonFoto1 = new javax.swing.JButton();
        jButtonFoto2 = new javax.swing.JButton();
        jButtonFoto3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("AGREGA LA INFORMACION DE TU EVENTO");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel7.setText("Musica en Evento");

        if(nombreEvento.getText().length()==0){
            nombreEvento.setText("Ingresa el nombre del evento");
            nombreEvento.setForeground(new Color(150, 150, 150));
        }
        nombreEvento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreEventoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreEventoFocusLost(evt);
            }
        });
        nombreEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreEventoActionPerformed(evt);
            }
        });

        if(ubicacionEvento.getText().length()==0){
            ubicacionEvento.setText("Ingresa la ubicacion del evento");
            ubicacionEvento.setForeground(new Color(150, 150, 150));
        }
        ubicacionEvento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ubicacionEventoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ubicacionEventoFocusLost(evt);
            }
        });

        if(precioEvento.getText().length()==0){
            precioEvento.setText("Ingresa el precio del evento");
            precioEvento.setForeground(new Color(150, 150, 150));
        }
        precioEvento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                precioEventoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                precioEventoFocusLost(evt);
            }
        });

        if(capacidadEvento.getText().length()==0){
            capacidadEvento.setText("Ingresa la capacidad de personas maxima del evento");
            capacidadEvento.setForeground(new Color(150, 150, 150));
        }
        capacidadEvento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                capacidadEventoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                capacidadEventoFocusLost(evt);
            }
        });

        if(artistaEvento.getText().length()==0){
            artistaEvento.setText("Ingresa el o la artista del evento");
            artistaEvento.setForeground(new Color(150, 150, 150));
        }
        artistaEvento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                artistaEventoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                artistaEventoFocusLost(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Electro", "Reguetton", "Rock", "Jazz", "Otro" }));

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel8.setText("Fotos del Evento");

        jButtonFoto1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonFoto1.setText("Escoger Foto");
        jButtonFoto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFoto1ActionPerformed(evt);
            }
        });

        jButtonFoto2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonFoto2.setText("Escoger Foto 2");
        jButtonFoto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFoto2ActionPerformed(evt);
            }
        });

        jButtonFoto3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonFoto3.setText("Escoger Foto 3");
        jButtonFoto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFoto3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(nombreEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(ubicacionEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(precioEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(capacidadEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(artistaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel7))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jButtonFoto1)
                .addGap(17, 17, 17)
                .addComponent(jButtonFoto2)
                .addGap(25, 25, 25)
                .addComponent(jButtonFoto3))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(jButton1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(nombreEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(ubicacionEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(precioEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(capacidadEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(artistaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addGap(11, 11, 11)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel8)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFoto2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFoto3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton1)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreEventoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        if(AgregarFoto.insertaFoto == true){
            agregaNombre = nombreEvento.getText();
            agregaUbicacion = ubicacionEvento.getText();
            agregaPrecio = Float.parseFloat(precioEvento.getText());
            agregaCantidad = Integer.parseInt(capacidadEvento.getText());
            agregaArtista = artistaEvento.getText();

           EventoAdministrador obj1 = new EventoAdministrador(agregaNombre,agregaUbicacion,agregaCantidad,agregaPrecio,agregaArtista);
           EventoAdministradorVerEventos obj2 = new EventoAdministradorVerEventos();
           this.dispose();
           obj2.setVisible(true);
        }        
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonFoto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFoto1ActionPerformed
       
       int resultado;
       File fichero;
       AgregarFoto obj1= new AgregarFoto();
       FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG y PNG", "jpg", "png");
       AgregarFoto.jFileCambia.setFileFilter(filtro);
       AgregarFoto.jFileCambia.setAcceptAllFileFilterUsed(false);
       resultado = AgregarFoto.jFileCambia.showOpenDialog(null);
       
         if (JFileChooser.APPROVE_OPTION == resultado) {
            fichero = obj1.jFileCambia.getSelectedFile();
            direccion = fichero.getPath();
         }
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonFoto1ActionPerformed

    private void jButtonFoto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFoto2ActionPerformed
       int resultado;
       File fichero2;
       AgregarFoto obj2= new AgregarFoto();
       FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG y PNG", "jpg", "png");
       AgregarFoto.jFileCambia.setFileFilter(filtro);
       AgregarFoto.jFileCambia.setAcceptAllFileFilterUsed(false);
       resultado = AgregarFoto.jFileCambia.showOpenDialog(null);
       
         if (JFileChooser.APPROVE_OPTION == resultado) {
            fichero2 = obj2.jFileCambia.getSelectedFile();
            direccion2 = fichero2.getPath();
         }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFoto2ActionPerformed

    private void jButtonFoto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFoto3ActionPerformed

       int resultado;
       File fichero3;
       AgregarFoto obj3= new AgregarFoto();
       FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG y PNG", "jpg", "png");
       AgregarFoto.jFileCambia.setFileFilter(filtro);
       AgregarFoto.jFileCambia.setAcceptAllFileFilterUsed(false);
       resultado = AgregarFoto.jFileCambia.showOpenDialog(null);
       
         if (JFileChooser.APPROVE_OPTION == resultado) {
            fichero3 = obj3.jFileCambia.getSelectedFile();
            direccion3 = fichero3.getPath();
         }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonFoto3ActionPerformed

    private void nombreEventoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreEventoFocusGained

          nombreEvento.setText("");
        nombreEvento.setForeground(new Color(50, 50, 50)); 

        // TODO add your handling code here:
    }//GEN-LAST:event_nombreEventoFocusGained

    private void nombreEventoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreEventoFocusLost

         if(nombreEvento.getText().length()==0){
            nombreEvento.setText("Ingresa el nombre del evento");
            nombreEvento.setForeground(new Color(150, 150, 150)); 
        } 
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreEventoFocusLost

    private void ubicacionEventoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ubicacionEventoFocusGained
      ubicacionEvento.setText("");
      ubicacionEvento.setForeground(new Color(50, 50, 50)); 
        
        // TODO add your handling code here:
    }//GEN-LAST:event_ubicacionEventoFocusGained

    private void ubicacionEventoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ubicacionEventoFocusLost
        
         if(ubicacionEvento.getText().length()==0){
           ubicacionEvento.setText("Ingresa la ubicacion del evento");
          ubicacionEvento.setForeground(new Color(150, 150, 150)); 
        } 

        // TODO add your handling code here:
    }//GEN-LAST:event_ubicacionEventoFocusLost

    private void precioEventoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_precioEventoFocusGained
         precioEvento.setText("");
         precioEvento.setForeground(new Color(50, 50, 50)); 
        
        // TODO add your handling code here:
    }//GEN-LAST:event_precioEventoFocusGained

    private void precioEventoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_precioEventoFocusLost
          if(precioEvento.getText().length()==0){
           precioEvento.setText("Ingresa el precio del evento");
          precioEvento.setForeground(new Color(150, 150, 150)); 
        } 
        
// TODO add your handling code here:
    }//GEN-LAST:event_precioEventoFocusLost

    private void artistaEventoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_artistaEventoFocusGained
        artistaEvento.setText("");
         artistaEvento.setForeground(new Color(50, 50, 50)); 
        
        // TODO add your handling code here:
    }//GEN-LAST:event_artistaEventoFocusGained

    private void capacidadEventoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_capacidadEventoFocusGained

         capacidadEvento.setText("");
         capacidadEvento.setForeground(new Color(50, 50, 50)); 
        // TODO add your handling code here:
    }//GEN-LAST:event_capacidadEventoFocusGained

    private void capacidadEventoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_capacidadEventoFocusLost

         if(capacidadEvento.getText().length()==0){
          capacidadEvento.setText("Ingresa la capacidad de personas maxima del evento");
          capacidadEvento.setForeground(new Color(150, 150, 150)); 
        } 
        // TODO add your handling code here:
    }//GEN-LAST:event_capacidadEventoFocusLost

    private void artistaEventoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_artistaEventoFocusLost
          if(artistaEvento.getText().length()==0){
          artistaEvento.setText("Ingresa el o la artista del evento");
         artistaEvento.setForeground(new Color(150, 150, 150)); 
        } 
        // TODO add your handling code here:
    }//GEN-LAST:event_artistaEventoFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventoAdministradorAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventoAdministradorAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventoAdministradorAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventoAdministradorAgregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventoAdministradorAgregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField artistaEvento;
    private javax.swing.JTextField capacidadEvento;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonFoto1;
    private javax.swing.JButton jButtonFoto2;
    private javax.swing.JButton jButtonFoto3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreEvento;
    private javax.swing.JTextField precioEvento;
    private javax.swing.JTextField ubicacionEvento;
    // End of variables declaration//GEN-END:variables
}
